[GAMEPLAY]
game_mode = survival
max_players = 16
pvp = false
pause_when_empty = true
vote_enabled = true

[NETWORK]
cluster_description = the b0rg will assimilate you
cluster_name = wonderland
cluster_password = 
cluster_intention = cooperative

[MISC]
console_enabled = true
enable_autosaver = true

[SHARD]
;;; Optimally a randomly generated key
cluster_key = ThisIsTheSecretKeyForClusterCommunication

shard_enabled = true
;;; Allows connections from other hosts
bind_ip = 0.0.0.0
master_ip = 127.0.0.1
master_port = 10889
